Updated process_cut() function to add default values to the patient_c…
pharmaverse/datacutr pull request #156
Opened 2023-03-06 17:02 UTC by reesnj

Hello @kieranjmartin and @barnett11,
As per issue #134 - I have added default values for the following function arguments:

- patient_cut_v = vector()
- date_cut_m = matrix(nrow=0, ncol=2)
- no_cut_v = vector()

In the reproducible examples provided in #134, these updates means that your first example should now work because no_cut_v will be set to the default value (an empty vector). However, your second example will still fail since it is expected that no_cut_v is a vector but you have set this to "" here. Hopefully this is clear from the documentation of the function but please let know if you think further updates are required.

2023-03-10 15:16 UTC, reesnj commented
Hello @barnett11 - thank you for your comments! 
I have updated the assertions to make the error messages more meaningful. Now, if you put in "", this will tell you that the input must be a vector, and also give you a note that if you do not want any domains to use this type of cut, then you should leave the parameter empty, rather than using "". 
Whereas, if you define a cut for an SDTM that is not in the input list, it will give a different error message indicating that there are inconsistencies between the input SDTMv datasets and the SDTMv datasets listed under each cut approach.
Hopefully you find these messages more informative!

2023-03-13 09:35 UTC, barnett11 requested changes
Looking good @reesnj - small update suggested

2023-03-13 09:35 UTC, barnett11 commented on R/process_cut.R
> +date_cut_m empty, in which a case default value of matrix(nrow=0, ncol=2) will be used."
```suggestion
date_cut_m empty, in which case a default value of matrix(nrow=0, ncol=2) will be used."
```

2023-03-15 09:34 UTC, kieranjmartin commented
Hi, I think this is fine if this is the solution which works, and making it default seems solid to me. That said, I think conventionally in R functions a blank argument would be expected to be NULL; my example with a missing string was probably not a good way to approach it either. 

I'm fine with it as is, however, as it is documented and asserted, so should be fine

2023-03-15 16:57 UTC, merged

2023-03-15 16:58 UTC, reesnj commented
Agreed to update this function at the next release to change the default values of function arguments to be NULL in order to follow a more conventional approach (task added to project board). However, agreed to leave this function as is for the current release.